name = "XMarkers"
prefix = "XMARK"
author = "XMARK"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3



files = [
    "mod.cpp",
    "README.md",
    "LICENSE",
    "extras/addons",
    "extras/keys",
    "AUTHORS.txt",
    "cow.paa",
    "icow.paa",
    "ncow.paa"
    ]

exclude = ["*.psd", "*.png", "*.tga"]

version = "1.0.0"
modname = "{{name}}"
key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"


check = [
    "!compile_scripts"
]

postbuild = [
    "!remove_compiled_scripts"
]

releasebuild = [
    "@zip @XMARK_{{version}}"
]

[header_exts]



[scripts.compile_scripts]
steps_windows = [
    "echo 'Compile Arma Scripts'",
    "ArmaScriptCompiler"
]

steps_linux = [
    "echo 'Compiling Arma Scripts does not work yet on Linux'"
]
only_release = true
show_output = false

[scripts.remove_compiled_scripts]
steps_windows = [
    "echo 'remove Compiled Scripts'",
    "powershell -Command Remove-Item './addons/*' -Recurse -Include *.sqfc"
]
steps_linux = [
    "echo 'Compiling Arma Scripts does not work yet on Linux'"
]
only_release = true
show_output = true